# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  name "bifrost"
  desc "A command-line utility to simplify connecting to AWS RDS/Redis instances through bastion hosts utilising AWS SSM Session Manager."
  homepage "https://github.com/b3nk3/bifrost"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost"
  depends_on cask: [
      "session-manager-plugin",
    ],
    formula: [
      "awscli",
      "gh",
    ]

  on_macos do
    on_intel do
      url "https://github.com/b3nk3/bifrost/releases/download/v#{version}/bifrost_Darwin_x86_64.tar.gz"
      sha256 "687e01c3be50c35dbee7d44fb28ed086a0ed9fa2c4b6c923391f86c98624509e"
    end
    on_arm do
      url "https://github.com/b3nk3/bifrost/releases/download/v#{version}/bifrost_Darwin_arm64.tar.gz"
      sha256 "6dca144db0958ad14eefaa225eb29a00dc18c1c7453382a0a27c142cf7cd7ecc"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bifrost"]
    end
  end

  # No zap stanza required
end
