# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  name "bifrost"
  desc "A command-line utility to simplify connecting to AWS RDS/Redis instances through bastion hosts utilising AWS SSM Session Manager."
  homepage "https://github.com/b3nk3/bifrost"
  version "0.9.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost"
  depends_on cask: [
      "session-manager-plugin",
    ],
    formula: [
      "awscli",
      "gh",
    ]

  on_macos do
    on_intel do
      url "https://github.com/b3nk3/bifrost/releases/download/v#{version}/bifrost_Darwin_x86_64.tar.gz"
      sha256 "83839fe1f6dfdafa3067abed5bff546c2f117f00325123380886edeb79f46806"
    end
    on_arm do
      url "https://github.com/b3nk3/bifrost/releases/download/v#{version}/bifrost_Darwin_arm64.tar.gz"
      sha256 "e753ded873cc3520b63a7f2b0d103e58791c8a56a3430c9b76c8d616dc5914bf"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bifrost"]
    end
  end

  # No zap stanza required
end
