# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  name "bifrost"
  desc "A command-line utility to simplify connecting to AWS RDS/Redis instances through bastion hosts utilising AWS SSM Session Manager."
  homepage "https://github.com/b3nk3/bifrost"
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost"
  depends_on cask: [
      "session-manager-plugin",
    ],
    formula: [
      "awscli",
      "gh",
    ]

  on_macos do
    on_intel do
      url "https://github.com/b3nk3/bifrost/releases/download/v#{version}/bifrost_Darwin_x86_64.tar.gz"
      sha256 "2244f0efb163217d5ccd7bd763ede55534bb94498064ba113eeb03fa693ba0d4"
    end
    on_arm do
      url "https://github.com/b3nk3/bifrost/releases/download/v#{version}/bifrost_Darwin_arm64.tar.gz"
      sha256 "9897e739aa624d86b4d54453d82a430882d7589ef92dd6b7bca05cbd7e890031"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bifrost"]
    end
  end

  # No zap stanza required
end
